# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-03-16 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_userbirthday_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
